# Generated by Django 6.0.6 on 2026-06-17 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_progress_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('title', 'category')},
        ),
    ]
