# Generated by Django 6.0.6 on 2026-07-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_lesson_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='completion',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
