# Generated by Django 6.0.6 on 2026-07-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_progress_completion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kslcard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='kslcard',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
